name: project
description: "A new Flutter project."
<<<<<<< HEAD
=======

>>>>>>> feature/booking
publish_to: 'none'

version: 1.0.0+1

environment:
<<<<<<< HEAD
  sdk: ^3.10.4
=======
  sdk: ^3.10.7
>>>>>>> feature/booking

dependencies:
  flutter:
    sdk: flutter

<<<<<<< HEAD
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.2.3
=======
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  http: ^1.2.2
>>>>>>> feature/booking

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
<<<<<<< HEAD
  uses-material-design: true
=======
  uses-material-design: true
>>>>>>> feature/booking
